version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    volumes:
      - .:/app
    command : "mvn clean verify"
  db:
    image: mariadb
#    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: test
